home/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *#homepage,login,logout,mainmenu,otp_verification
app_name='home'

urlpatterns = [
    path('homepage/',homepage,name='homepage'),
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),
    path('mainmenu/',mainmenu,name='mainmenu'),
    path('login/home/otp_verification/',otp_verification,name='otp_verification'),
    path('create_new_user/',create_new_user,name='create_new_user'),
    #path('calculator/',calculator,name='calculator'),
    path('masterlogin/',masterlogin,name='masterlogin'),
    
]

pvrvl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from home import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('home/',include('home.urls')),
    #path('main/',include('main.urls')),

    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="home/password_reset.html"),name="reset_password"),

    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="home/password_reset_sent.html"),name="password_reset_done"),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="home/password_reset_confirm.html"),name="password_reset_confirm"),

    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="home/password_reset_complete.html"),name="password_reset_complete"),
]

home/models.py
from django.db import models
from django.db.models.signals import post_save,pre_save
from django.contrib.auth.models import User
from django.dispatch import receiver

# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	company_name = models.CharField(max_length=255,null=True,blank=True)
	#address
	#phone
	#mobile


	def __str__(self):
		return self.user.username

@receiver(post_save,sender=User)
def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:

    	userprofile = UserProfile.objects.create(user=instance)

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import auth,User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
#from .models import userprofile
import datetime 
import random
import smtplib
from django.core.mail import EmailMessage
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.
def homepage(request):
	return render(request,"home/home.html")
def login(request):
	if request.method == 'POST':
	
		request.session["uname"] = request.POST['e']
		request.session["password"] = request.POST['p']
		
		userd =auth.authenticate(request,username=request.session["uname"],password=request.session["password"])
		if userd is not None:
			
			u = User.objects.get(username=request.session["uname"])
			
			otp = random.randrange(111111, 999999)
			request.session["o"] = otp
			
			email = EmailMessage()
			email.subject = 'PVRVL OTP'
			email.body = str(otp)
			email.from_email = 'pvrvlotp@gmail.com'
			email.to = [u.email]
			email.send()

			return redirect('home:otp_verification')

		else:
			messages.warning(request,'inavalid details,')
			return render(request,'home/login.html',{'password':request.session["password"],'username':request.session["uname"]})

	else:
		return render (request,'home/login.html')


def otp_verification(request):
	if request.method=='POST':
		request.session["o2"] = int(request.POST['otp1'])
		userd =auth.authenticate(request,username=request.session["uname"],password=request.session["password"])
		if request.session["o2"] == request.session["o"]:
			auth.login(request,userd)
			return redirect("home:homepage")

		else:
			messages.warning(request,'enter correct otp') 
			return render(request,'home/otp.html')
	else:
		return render(request,'home/otp.html')


@login_required	
def logout(request):
	auth.logout(request)
	return redirect("home:mainmenu")


@login_required
def create_new_user(request):
	if request.method == 'POST':
		user_name = request.POST.get('usrname')
		password = request.POST.get('psw')
		email = request.POST.get('email')

		if User.objects.filter(username=user_name):
			messages.warning(request,'User name Already Taken') 
			return render(request,"home/create_new_user.html",{'u':user_name,'e':email,'p':password})
		elif User.objects.filter(email=email):
			messages.warning(request,'Email Already Registred')
			return render(request,"home/create_new_user.html",{'u':user_name,'e':email,'p':password})
		else:
			user = User.objects.create_user(username=user_name,email=email,password=password)
			messages.info(request,'User Created Successfully...')
			return render(request,"home/create_new_user.html")

	else:
		return render (request,'home/create_new_user.html')


def mainmenu(request):
    return render(request, 'home/mainmenu.html', {})


@login_required
@staff_member_required
def masterlogin(request):
	if request.method == 'POST':

		#user = authenticate(request, username=request.POST['username'],password='Ravi@1234')
		user = request.POST['username']
		#if user is not None:
		users = User.objects.filter(username=user)
		for u in users:
			auth.login(request,u)
			return redirect('home:homepage')

		else:
			messages.warning(request,'inavalid details,')
			return render(request,'home/login_as_user.html')
	else:
		return render (request,'home/login_as_user.html')

'''def fgpassword(request):
	return render(request,'forgot.html')

@login_required	
def calculator(request):
    return render(request, 'home/calculator.html', {})'''

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <title>Pvrvl Accounting</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

</head>

<style type="text/css">
    *{
      margin: 1;
      padding: 1px;
      box-sizing: border-box;
      font-family: 'Montserrat', sans-serif;
    }
    .footer {
        border-radius: 4px;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #1C1C1C ;
        color: white;
        text-align: center;
    }
    a{
      color: black;
    }
    .navbar-brand {
      font-weight: 900;
      font-size: 1.4em;
    }

    .navbar-brand .letter {
      display: inline-block;
      line-height: 1em;
    }
    @media only screen and (max-width: 767px) {
      .c_name { font-size: 22px !important; }
    }
</style>


<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <h4 class="navbar-brand" ><strong>PVRVL Accounting</strong></h4>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      {% if user.is_authenticated %}
        <a class="nav-link active" href='{% url "home:homepage" %}' accesskey="h"><strong>H</strong>ome</a>
        <a class="nav-link active" href="#" accesskey="l"><strong>L</strong>edgers</a>
        <a class="nav-link active" href="#" accesskey="j"><strong>J</strong>v</a>
        <a class="nav-link active" href="#" accesskey="t"><strong>T</strong>railBalance</a>

        {% if user.is_superuser %}
        <a class="nav-link active" href='{% url "home:create_new_user" %}' accesskey="u"><i class="fa fa-user-plus" aria-hidden="true"></i><strong>U</strong>ser</a>
        <a class="nav-link active" href='{% url "home:masterlogin" %}' accesskey="u">User Log</a>
        {% endif %}
        <a class="nav-link active" href='{% url "home:logout" %}'> <i class="fa fa-sign-out" aria-hidden="true"></i> Signout</a>
        {% else %}
        <a class="nav-link active" href='{% url "home:login" %}'> <i class="fa fa-sign-in" aria-hidden="true"></i> Signin</a>
        {% endif %}
    </div>
  </div>
</nav>
<br><br><br>
<i class="fa fa-arrow-left" aria-hidden="true" onclick="window.history.back()"></i>
{% now "jS F Y H:i" %}
<h2 class="c_name" align="center">{{ user.userprofile.company_name }}</h2><br>
{% if messages %}
  {% for message in messages %}
      <p id="alert" align="center" style="color:green"; ><b>{{ message }}</b>
      <i class="fa fa-times" aria-hidden="true" id="hide"></i></p>
  {% endfor %}
{% endif %}


<div class="container">
  {% block content %}
  {% endblock %}
</div>

</body>
<script>

$(document).ready(function(){
  $("#hide").click(function(){
    $("#alert").hide();
  });
});

// Wrap every letter in a span
var textWrapper = document.querySelector('.navbar-brand');
textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

anime.timeline({loop: true})
  .add({
    targets: '.navbar-brand .letter',
    scale: [4,1],
    opacity: [0,1],
    translateZ: 0,
    easing: "easeOutExpo",
    duration: 950,
    delay: (el, i) => 70*i
  }).add({
    targets: '.navbar-brand',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 1000
  });
</script>
</html>

templates/home/calculator.html
{% extends 'base.html' %}
{% block content %}
	<head>

		<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

		<title>A simple calculator</title>

		<style type="text/css">
			body{
			font-family: 'Montserrat', sans-serif;
			background-color: white;
		}
		#container{
			width: 1000px;
			height: 550px;
			
			margin: 20px auto;	
		}
		#calculator{
			width: 320px;
			height: 520px;
			background-color: #eaedef;
			margin: 0 auto;
			top: 20px;
			position: relative;
			border-radius: 5px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
		}
		#result{
			height: 120px;
		}
		#history{
			text-align: right;
			height: 20px;
			margin: 0 20px;
			padding-top: 20px;
			font-size: 15px;
			color: #919191;
		}
		#output{
			text-align: right;
			height: 60px;
			margin: 10px 20px;
			font-size: 30px;
		}
		#keyboard{
			height: 400px;
		}
		.operator, .number, .empty{
			width: 50px;
			height: 50px;
			margin: 15px;
			float: left;
			border-radius: 50%;
			border-width: 0;
			font-weight: bold;
			font-size: 15px;
		}
		.number, .empty{
			background-color: #eaedef;
		}
		.number, .operator{
			cursor: pointer;
		}
		.operator:active, .number:active{
			font-size: 13px;
		}
		.operator:focus, .number:focus, .empty:focus{
			outline: 0;
		}
		button:nth-child(4){
			font-size: 20px;
			background-color: #20b2aa;
		}
		button:nth-child(8){
			font-size: 20px;
			background-color: #ffa500;
		}
		button:nth-child(12){
			font-size: 20px;
			background-color: #f08080;
		}
		button:nth-child(16){
			font-size: 20px;
			background-color: #7d93e0;
		}
		button:nth-child(20){
			font-size: 20px;
			background-color: #9477af;
		}
		</style>
	</head>
	<body>
		<div id="container">
			<div id="calculator">
				<div id="result">
					<div id="history">
						<p id="history-value"></p>
					</div>
					<div id="output">
						<p id="output-value"></p>
					</div>
				</div>
				<div id="keyboard">
					<button class="operator" accesskey="c" id="clear">C</button>
					<button class="operator" accesskey="e" id="backspace">CE</button>
					<button class="operator" accesskey="%" id="%">%</button>
					<button class="operator" accesskey="/" id="/">&#247;</button>
					<button class="number" accesskey="7" id="7">7</button>
					<button class="number" accesskey="8" id="8">8</button>
					<button class="number" accesskey="9" id="9">9</button>
					<button class="operator" accesskey="*" id="*">&times;</button>
					<button class="number" value="4" onclick="dis('4')" id="4">4</button>
					<button class="number" accesskey="5" id="5">5</button>
					<button class="number" accesskey="6" id="6">6</button>
					<button class="operator" accesskey="-" id="-">-</button>
					<button class="number" accesskey="1" id="1">1</button>
					<button class="number" accesskey="2" id="2">2</button>
					<button class="number" accesskey="3" id="3">3</button>
					<button class="operator" accesskey="+" id="+">+</button>
					<button class="empty" id="empty"></button>
					<button class="number" accesskey="0" id="0">0</button>
					<button class="empty" id="empty"></button>
					<button class="operator" accesskey="=" id="=">=</button>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			function getHistory(){
		return document.getElementById("history-value").innerText;
		}
		function printHistory(num){
			document.getElementById("history-value").innerText=num;
		}
		function getOutput(){
			return document.getElementById("output-value").innerText;
		}
		function printOutput(num){
			if(num==""){
				document.getElementById("output-value").innerText=num;
			}
			else{
				document.getElementById("output-value").innerText=getFormattedNumber(num);
			}	
		}
		function getFormattedNumber(num){
			if(num=="-"){
				return "";
			}
			var n = Number(num);
			var value = n.toLocaleString("en");
			return value;
		}
		function reverseNumberFormat(num){
			return Number(num.replace(/,/g,''));
		}
		var operator = document.getElementsByClassName("operator");
		for(var i =0;i<operator.length;i++){
			operator[i].addEventListener('click',function(){
				if(this.id=="clear"){
					printHistory("");
					printOutput("");
				}
				else if(this.id=="backspace"){
					var output=reverseNumberFormat(getOutput()).toString();
					if(output){//if output has a value
						output= output.substr(0,output.length-1);
						printOutput(output);
					}
				}
				else{
					var output=getOutput();
					var history=getHistory();
					if(output==""&&history!=""){
						if(isNaN(history[history.length-1])){
							history= history.substr(0,history.length-1);
						}
					}
					if(output!="" || history!=""){
						output= output==""?output:reverseNumberFormat(output);
						history=history+output;
						if(this.id=="="){
							var result=eval(history);
							printOutput(result);
							printHistory("");
						}
						else{
							history=history+this.id;
							printHistory(history);
							printOutput("");
						}
					}
				}
				
			});
		}
		var number = document.getElementsByClassName("number");
		for(var i =0;i<number.length;i++){
			number[i].addEventListener('click',function(){
				var output=reverseNumberFormat(getOutput());
				if(output!=NaN){ //if output is a number
					output=output+this.id;
					printOutput(output);
				}
			});
		}
		</script>
	</body>
{% endblock %}

templates/home/create_new_user.html
{% extends 'base.html' %}
{% block content %}
<style>
/* Style all input fields */
input {
  width: 50%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 2px;
  margin-bottom: 16px;
}

/* Style the submit button */
button {
  background-color: black;
  color: white;
}

/* Style the container for inputs */
.container {
  background-color: white;
  padding: 10px;
}

/* The message box is shown when the user clicks on the password field */
#message {
  display:none;
  background: #f1f1f1;
  color: #000;
  position: relative;
  padding: 40px;
  margin-top: 10px;
}

#message p {
  padding: 10px 35px;
  font-size: 18px;
}

/* Add a green text color and a checkmark when the requirements are right */
.valid {
  color: green;
}

.valid:before {
  position: relative;
  left: -35px;
  content: "✔";
}

/* Add a red text color and an "x" when the requirements are wrong */
.invalid {
  color: red;
}

.invalid:before {
  position: relative;
  left: -35px;
  content: "✖";
}
</style>

<div class="container" align="center">
  <form method="POST" autocomplete="off">
  	{% csrf_token %}
  	<h2 align="center">CREATE NEW USER</h2>
    <input type="text" id="usrname" name="usrname" value="{{u}}" placeholder="Username" required><br>

    <input type="email" id="email" name="email" value="{{e}}" placeholder="Email" required><br>

    <input type="password" id="psw" placeholder="Password" value="{{p}}" name="psw" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required><br>
    
    <button class="btn btn-dark">Submit</button>
  </form>
</div>

<div id="message">
  <h3>Password must contain the following:</h3>
  <p id="letter" class="invalid">A <b>lowercase</b> letter</p>
  <p id="capital" class="invalid">A <b>capital (uppercase)</b> letter</p>
  <p id="number" class="invalid">A <b>number</b></p>
  <p id="length" class="invalid">Minimum <b>8 characters</b></p>
</div>

<script>
var myInput = document.getElementById("psw");
var letter = document.getElementById("letter");
var capital = document.getElementById("capital");
var number = document.getElementById("number");
var length = document.getElementById("length");

// When the user clicks on the password field, show the message box
myInput.onfocus = function() {
  document.getElementById("message").style.display = "block";
}

// When the user clicks outside of the password field, hide the message box
myInput.onblur = function() {
  document.getElementById("message").style.display = "none";
}

// When the user starts to type something inside the password field
myInput.onkeyup = function() {
  // Validate lowercase letters
  var lowerCaseLetters = /[a-z]/g;
  if(myInput.value.match(lowerCaseLetters)) {  
    letter.classList.remove("invalid");
    letter.classList.add("valid");
  } else {
    letter.classList.remove("valid");
    letter.classList.add("invalid");
  }
  
  // Validate capital letters
  var upperCaseLetters = /[A-Z]/g;
  if(myInput.value.match(upperCaseLetters)) {  
    capital.classList.remove("invalid");
    capital.classList.add("valid");
  } else {
    capital.classList.remove("valid");
    capital.classList.add("invalid");
  }

  // Validate numbers
  var numbers = /[0-9]/g;
  if(myInput.value.match(numbers)) {  
    number.classList.remove("invalid");
    number.classList.add("valid");
  } else {
    number.classList.remove("valid");
    number.classList.add("invalid");
  }
  
  // Validate length
  if(myInput.value.length >= 8) {
    length.classList.remove("invalid");
    length.classList.add("valid");
  } else {
    length.classList.remove("valid");
    length.classList.add("invalid");
  }
}
</script>
{% endblock %}

templates/home/home.html
{% extends 'base.html' %}
{% block content %}
<style type="text/css">
  .bg-primary {
    background-color: #069A98 !important;
  }

  .btn-primary {
    background-color: #069A98 !important;
    border: none;
  }

  .bg-success {
    background-color: #B3C913 !important;
  }

  .btn-success {
    background-color: #B3C913 !important;
    border: none;
  }
</style>
<div class="container">
  <div class="card-deck">

    <div class="card bg-danger">
      <div class="card-body text-center">
        <a href="#" role="button" class="btn btn-danger" style="height: 80px;width: 200px;" accesskey="s" ><strong>S</strong>ALES <br><small>alt+s</small></a>
      </div>
    </div>

    <div class="card bg-warning">
      <div class="card-body text-center">
        <a href="#" class="btn btn-warning" style="height: 80px;width: 200px;" accesskey="p"><strong>P</strong>URCHSES <br><small>alt+p</small></a>
      </div>
    </div>

    <div class="card bg-success">
      <div class="card-body text-center">
        <strong>RECEIPTS</strong><br>
        <button class="btn btn-success" accesskey="r"><a href="#">Bank</a></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-success" accesskey="c"><a href="#">Cash</a></button><br>
        <small>alt+r &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; alt+c</small>
      </div>
    </div>

    <div class="card bg-primary">
      <div class="card-body text-center">
        <strong>PAYMENTS</strong><br>
        <button class="btn btn-primary" accesskey="y"><a href="#">Bank</a></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary" accesskey="a"><a href="#">Cash</a></button><br>
        <small>alt+y &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; alt+a</small>
      </div>
    </div>  

  </div>

  <br><br>

  <div class="card-deck">

    <div class="card bg-light">
      <div class="card-body text-center">
        <button class="btn btn-dark" accesskey="m"><a href="#" style="color: white";><strong>M</strong>ASTER</a></button><br><small>alt+m</small>
        <br><p ><h6> <button class="btn btn-dark"> <a href="#" style="color: white";>Party</a> </button> <button class="btn btn-dark"> <a href="#" style="color: white";>Product</a> </button> <button class="btn btn-dark"> <a href="#" style="color: white";>Bank</a> </button> <button class="btn btn-dark"> <a href="#" style="color: white";>Head</a> </button> </h6></p> 
      </div>
    </div>

    <div class="card bg-dark">
      <div class="card-body text-center">
        <button class="btn btn-light"><strong>REPORTS</strong></button><br>
        <p><br><h6>
          <button class="btn btn-light"> <a href="#">Sale</a> </button> <button class="btn btn-light"> <a href="#">Purchase</a> </button> <button class="btn btn-light"> <a href="#">Receipt</a> </button> <button class="btn btn-light"> <a href="#">Payment</a> </button>
        </h6></p>
      </div>
    </div>

  </div>

  <br><br>

  <div class="card-deck">

    <div class="card bg-secondary">
      <div class="card-body text-center">
        <button class="btn btn-warning"><strong>CONTRA</strong></button><br>
        <p style="color: white";><br><h6 style="color: white";><button class="btn btn-secondary">Withdraw</button> &nbsp; <button class="btn btn-secondary">Deposit</button> &nbsp; <button class="btn btn-secondary">Transfer</button></h6></p> 
      </div>
    </div>

</div>

{% endblock %}

templates/home/logout.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #00ff80;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
.body{
      background-color: #e5eecc;
      padding: 25px;
      margin: 20px;
    }
  header {
  background-color: #666;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

.big {
   padding: 15px 15px 15px 32px;
  font-size: 50px;
  color: #818181;
  display: block;
  padding: 30px;
  text-align: center;
  font-size: 35px;
}

.big span:hover {
  color: green;
        background-color: red;
}

</style>
    <h1 class="big">Successfully Log outed</h1>
</head>
<body class="body">
{% load static %}
{% if user.is_authenticated %}
<div align="right">
<a>Logged User : {{ user.get_username }}  </a>
    <a href='{% url "logout" %}' class="btn btn-primary" role="button"> Logout </a>
{% else %}
    <p>Please log in.</p>
    <a href='{% url "home:login" %}' class="btn btn-primary" role="button"> Login </a> <br><br>
    <a href='{% url "home:homepage" %}' class="btn btn-primary" role="button"> Home </a>
{% endif %}

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
</div>
</body>
</html>

templates/home/password_reset_complete.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-img {
{% load static %}
  /* The image used */
  /*background-image: url("{% static '/images/car-insurance.jpg' %}");*/

  min-height: 380px;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Add styles to the form container */
.container {
  position: absolute;
  right: 0;
  margin: 20px;
  max-width: 300px;
  padding: 16px;
  background-color: #e5eecc;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit button */
.btn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
.body{
      background-color: #e5eecc;
      padding: 25px;
      margin: 20px;
    }
</style>
</head>
<body class="body">
<h1 align="center"> Reset Password</h1>
<div class="bg-img">
  
<p>
    Your password has been set. You may go ahead and <a href="{% url 'home:login' %}">sign in</a> now.
  </p>
  
</div>

  
  

</body>
</html>